const musicList = [
    {
        id: 1,
        name: 'Chờ đợi có đáng sợ',
        singer: 'ANDIEZ',
        linkAu: 'ChoDoiCoDangSo.mp3',
        img: './assests/img/ChoDoiCoDangSoImg.jpg',
    },
    {
        id: 2,
        name: 'Hẹn em kiếp sau',
        singer: 'Lã. x Duy Phúc x TiB',
        linkAu: 'HenEmKiepSau.mp3',
        img: './assests/img/HenEmKiepSau.jpg',
    },
    {
        id: 3,
        name: 'Lạc vào trong mơ',
        singer: 'Simon C ft. Wuy',
        linkAu: 'LacVaoTrongMo.mp3',
        img: './assests/img/LacVaoTrongMo.jpg',
    },
    {
        id: 4,
        name: 'Anh thề đấy',
        singer: 'Thanh Hưng',
        linkAu: 'AnhTheDay.mp3',
        img: './assests/img/AnhTheDay.jpg',
    },
    {
        id: 5,
        name: '100 year love',
        singer: 'NamDuc',
        linkAu: '100YearLove.mp3',
        img: './assests/img/100YearLove.jpg',
    },
    {
        id: 6,
        name: 'Nơi này có anh',
        singer: 'Sơn Tùng M-TP',
        linkAu: 'NoiNayCoAnh.mp3',
        img: './assests/img/NoiNayCoAnh.jpg',
    },
    {
        id: 7,
        name: 'Làm người luôn yêu em',
        singer: 'Sơn Tùng M-TP',
        linkAu: 'LamNguoiLuonYeuEm.mp3',
        img: './assests/img/LamNguoiLuonYeuEm.jpg',
    },
    {
        id: 8,
        name: 'Đếm Ngày Xa Em',
        singer: 'Only C ft. Lou Hoàng',
        linkAu: 'DemNgayXaEm.mp3',
        img: './assests/img/DemNgayXaEm.jpg',
    },
    {
        id: 9,
        name: 'Không phải dạng vừa đâu',
        singer: 'Sơn Tùng M-TP',
        linkAu: 'KhongPhaiDangVuaDau.mp3',
        img: './assests/img/KhongPhaiDangVuaDau.jpg',
    },
    {
        id: 10,
        name: 'Thê lương',
        singer: 'PHÚC CHINH',
        linkAu: 'TheLuong.mp3',
        img: './assests/img/TheLuong.jpg',
    },
    {
        id: 11,
        name: 'Mặt mộc',
        singer: 'Phạm Nguyên Ngọc x VAnh x Ân Nhi',
        linkAu: 'MatMoc.mp3',
        img: './assests/img/MatMoc.jpg',
    },
    {
        id: 12,
        name: 'Lỡ thương một người',
        singer: 'Nguyễn Đình Vũ',
        linkAu: 'LoThuongMotNguoi.mp3',
        img: './assests/img/LoThuongMotNguoi.jpg',
    },
    {
        id: 13,
        name: 'Yêu 5',
        singer: 'Rhymastic',
        linkAu: 'Yeu5.mp3',
        img: './assests/img/Yeu5.jpg',
    },
    {
        id: 14,
        name: 'Chỉ muốn bên em lúc này',
        singer: 'JIKI X ft HUY VẠC',
        linkAu: 'ChiMuonBenEmLucNay.mp3',
        img: './assests/img/ChiMuonBenEmLucNay.jpg',
    },
    {
        id: 15,
        name: 'Sau tất cả',
        singer: 'ERIK',
        linkAu: 'SauTatCa.mp3',
        img: './assests/img/SauTatCa.jpg',
    },
    {
        id: 16,
        name: 'Như phút ban đầu',
        singer: 'Noo Phước Thịnh',
        linkAu: 'NhuPhutBanDau.mp3',
        img: './assests/img/NhuPhutBanDau.jpg',
    },
    {
        id: 17,
        name: 'Lời yêu ngây dại',
        singer: 'Kha x MewMew',
        linkAu: 'LoiYeuNgayDai.mp3',
        img: './assests/img/LoiYeuNgayDai.jpg',
    },
    {
        id: 18,
        name: 'Đường tôi chở em về',
        singer: 'buitruonglinh',
        linkAu: 'DuongToiChoEmVe.mp3',
        img: './assests/img/DuongToiChoEmVe.jpg',
    },
    {
        id: 19,
        name: 'Anh đã từ bỏ rồi đấy',
        singer: 'Nguyenn x Aric',
        linkAu: 'AnhDaTuBoRoiDay.mp3',
        img: './assests/img/AnhDaTuBoRoiDay.jpg',
    },
    {
        id: 20,
        name: 'Gió',
        singer: 'Jank',
        linkAu: 'Gio.mp3',
        img: './assests/img/Gio.jpg',
    },
    {
        id: 21,
        name: 'Những gì anh nói',
        singer: 'BOZITT',
        linkAu: 'NhungGiAnhNoi.mp3',
        img: './assests/img/NhungGiAnhNoi.jpg',
    },
    {
        id: 22,
        name: 'Hoa cỏ lau',
        singer: 'Phong Max',
        linkAu: 'HoaCoLau.mp3',
        img: './assests/img/HoaCoLau.jpg',
    },
    {
        id: 23,
        name: 'Tỏ tình',
        singer: 'K-ICM ft. JANG NGUYEN',
        linkAu: 'ToTinh.mp3',
        img: './assests/img/ToTinh.jpg',
    },
    {
        id: 24,
        name: 'Như anh đã thấy em',
        singer: 'PhucXp ft. Freak D',
        linkAu: 'NhuAnhDaThayEm.mp3',
        img: './assests/img/NhuAnhDaThayEm.jpg',
    },
    {
        id: 25,
        name: 'Ánh sao và bầu trời',
        singer: 'T.R.I x Cá',
        linkAu: 'AnhSaoVaBauTroi.mp3',
        img: './assests/img/AnhSaoVaBauTroi.jpg',
    },
    {
        id: 26,
        name: 'Âm thầm bên em',
        singer: 'SƠN TÙNG MTP',
        linkAu: 'AmThamBenEm.mp3',
        img: './assests/img/AmThamBenEm.jpg',
    },
    {
        id: 27,
        name: 'Cẩm tú cầu',
        singer: 'RAYO x HUỲNH VĂN',
        linkAu: 'CamTuCau.mp3',
        img: './assests/img/CamTuCau.jpg',
    },
    {
        id: 28,
        name: 'Hứa đợi nhưng chẳng tới',
        singer: 'Lâm Tuấn X Vương Thiên Tuấn',
        linkAu: 'HuaDoiNhungChangToi.mp3',
        img: './assests/img/HuaDoiNhungChangToi.jpg',
    },
    {
        id: 29,
        name: 'Người dưng',
        singer: 'Jack - J97',
        linkAu: 'NguoiDung.mp3',
        img: './assests/img/NguoiDung.jpg',
    },
    {
        id: 30,
        name: 'Lưu niên',
        singer: 'Jack - J97',
        linkAu: 'LuuNien.mp3',
        img: './assests/img/LuuNien.jpg',
    },
    {
        id: 31,
        name: 'Nếu phải giữ cho em',
        singer: 'Jack - J97',
        linkAu: 'NeuPhaiGiuChoEm.mp3',
        img: './assests/img/NeuPhaiGiuChoEm.jpg',
    },
    {
        id: 32,
        name: 'Mỗi lần nhớ em là một ngày mưa',
        singer: 'Jack - J97',
        linkAu: 'MoLanNhoEmLaMotNgayMua.mp3',
        img: './assests/img/MoLanNhoEmLaMotNgayMua.jpg',
    },
    {
        id: 33,
        name: 'Hào hoa',
        singer: 'Jack - J97',
        linkAu: 'HaoHoa.mp3',
        img: './assests/img/HaoHoa.jpg',
    },
    {
        id: 34,
        name: 'Hướng dương bất tức',
        singer: 'Jack - J97',
        linkAu: 'HuongDuongBatTuc.mp3',
        img: './assests/img/HuongDuongBatTuc.jpg',
    },
];

export { musicList };
